###
POST http://localhost:3001/api/course HTTP/1.1
Content-Type: application/json

    [
  {  "courseoccasionid": 28,
    "userid": 47,
    "testid": 2}, 
    {
            "courseoccasionid": 28,
    "userid": 46,
    "testid": 2
    }
    ]


###
GET http://localhost:3001/api/course HTTP/1.1
