###
POST http://localhost:3001/api/course HTTP/1.1
Content-Type: application/json

    [
  {  "courseoccasionid": 60,
    "userid": 1,
    "testid": 2}, 
    {
            "courseoccasionid": 50,
    "userid": 3,
    "testid": 2
    }
    ]


###
GET  http://localhost:3001/api/course/ HTTP/1.1
