POST http://localhost:3001/api/courseoccasion HTTP/1.1
Content-Type: application/json

{
    "name": "Kurs6",
    "startdate": "2022-11-11",
    "enddate":"2022-12-12",
    "courseorganizer":"test"
    
}
###
DELETE  http://localhost:3001/api/course/8

###

GET http://localhost:3001/api/courseoccasion HTTP/1.1